FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY index.html ./
COPY vite.config.js ./
COPY src ./src

# cache-bust: 2026-08-08
EXPOSE 3000

CMD sh -c "npm run dev -- --host 0.0.0.0 --port ${PORT:-3000}"
