CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  author VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'Founder',
  company_id VARCHAR(64),
  company_name VARCHAR(255),
  company_domain VARCHAR(255),
  linkedin_company_url VARCHAR(500),
  company_verified BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS users_unique_founder_company
ON users (company_id)
WHERE role = 'Founder' AND company_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS sessions (
  id SERIAL PRIMARY KEY,
  token VARCHAR(255) UNIQUE NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS companies (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  sector VARCHAR(100) NOT NULL,
  summary TEXT NOT NULL,
  growth VARCHAR(50) NOT NULL,
  retention VARCHAR(50) NOT NULL,
  pipeline VARCHAR(50) NOT NULL,
  hubspot_status VARCHAR(100) NOT NULL,
  rating VARCHAR(50) NOT NULL,
  review VARCHAR(255) NOT NULL,
  metrics_sharing VARCHAR(30) NOT NULL,
  hubspot_deals VARCHAR(100) NOT NULL,
  hubspot_campaigns VARCHAR(100) NOT NULL,
  hubspot_meetings VARCHAR(100) NOT NULL,
  hubspot_portal VARCHAR(100),
  hubspot_owner VARCHAR(100),
  hubspot_connected_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vendors (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  tier VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS meetings (
  id VARCHAR(64) PRIMARY KEY,
  company_id VARCHAR(64) NOT NULL,
  topic VARCHAR(255) NOT NULL,
  schedule VARCHAR(100) NOT NULL,
  visibility VARCHAR(255) NOT NULL,
  host VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS feed_items (
  id VARCHAR(64) PRIMARY KEY,
  author VARCHAR(100) NOT NULL,
  detail TEXT NOT NULL,
  time VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS company_metrics (
  id SERIAL PRIMARY KEY,
  company_id VARCHAR(64) NOT NULL,
  source_type VARCHAR(50) NOT NULL,
  verification_status VARCHAR(50) NOT NULL,
  confidence_score DOUBLE PRECISION NOT NULL,
  metric_key VARCHAR(100) NOT NULL,
  metric_value DOUBLE PRECISION NOT NULL,
  captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS intro_requests (
  id SERIAL PRIMARY KEY,
  requester_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  vendor_id VARCHAR(64) NOT NULL,
  message TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engagements (
  id SERIAL PRIMARY KEY,
  requester_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id VARCHAR(64) NOT NULL,
  vendor_id VARCHAR(64) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  pricing_model VARCHAR(30) NOT NULL DEFAULT 'milestone',
  consultant_fee DOUBLE PRECISION NOT NULL DEFAULT 0,
  fee_currency VARCHAR(10) NOT NULL DEFAULT 'USD',
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engagement_messages (
  id SERIAL PRIMARY KEY,
  engagement_id INTEGER NOT NULL REFERENCES engagements(id) ON DELETE CASCADE,
  author_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  author_name VARCHAR(100) NOT NULL,
  channel VARCHAR(30) NOT NULL DEFAULT 'chat',
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engagement_milestones (
  id SERIAL PRIMARY KEY,
  engagement_id INTEGER NOT NULL REFERENCES engagements(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'planned',
  payment_provider VARCHAR(30),
  payment_reference VARCHAR(255),
  due_date TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE engagement_milestones ADD COLUMN IF NOT EXISTS payment_provider VARCHAR(30);
ALTER TABLE engagement_milestones ADD COLUMN IF NOT EXISTS payment_reference VARCHAR(255);

CREATE TABLE IF NOT EXISTS engagement_calls (
  id SERIAL PRIMARY KEY,
  engagement_id INTEGER NOT NULL REFERENCES engagements(id) ON DELETE CASCADE,
  provider VARCHAR(30) NOT NULL,
  meeting_url TEXT NOT NULL,
  agenda TEXT,
  scheduled_at TIMESTAMP NOT NULL,
  created_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS engagement_outcomes (
  engagement_id INTEGER PRIMARY KEY REFERENCES engagements(id) ON DELETE CASCADE,
  baseline_growth DOUBLE PRECISION NOT NULL DEFAULT 0,
  current_growth DOUBLE PRECISION NOT NULL DEFAULT 0,
  baseline_retention DOUBLE PRECISION NOT NULL DEFAULT 0,
  current_retention DOUBLE PRECISION NOT NULL DEFAULT 0,
  baseline_pipeline DOUBLE PRECISION NOT NULL DEFAULT 0,
  current_pipeline DOUBLE PRECISION NOT NULL DEFAULT 0,
  roi_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
  last_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_notifications (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(60) NOT NULL,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  related_engagement_id INTEGER REFERENCES engagements(id) ON DELETE SET NULL,
  read_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
